WIP: Region production
OPM/opm-output pull request #106
Opened 2016-10-11 12:40 UTC by joakim-hove

This is on top of #101 - which should be merged first.

2016-10-25 16:31 UTC, jokva commented
Starting to look good!

Just a general observation: most std::containers have `empty` in addition to `size`. Other than that it's generally preferred to use `iostream` rather than printf, mostly because mixing the two isn't all that nice and printf's less flexible and type safe, and other opm modules already use iostream.

2016-10-25 16:43 UTC, joakim-hove commented
> Other than that it's generally preferred to use iostream rather than printf

Yes - the `printf( )` was just debugging; but my oh my quick and dirty formatted output with `iostream` is painful.

2016-10-25 16:44 UTC, jokva commented
> Yes - the printf( ) was just debugging; but my oh my quick and dirty formatted output with iostream is painful.

amen brother, it's dreadful. It has plenty of nice features, but is slow and clumsy for quick one-offs.

2016-10-25 17:30 UTC, atgeirr commented
> quick and dirty formatted output with iostream is painful.

Oh yes. For me, C printf is also painful... The only language I have ever found it easy to format output in was perl, unfortunately!

2016-10-25 19:17 UTC, jokva commented
Perl is love, perl is life. Perl's great, python isn't too bad, I think Haskell is nice too and I suppose the lisps have some niceness to them (at least if you pimp it a bit with macros).

Regardless, iostreams are clunky but they do have some nice features. Rare you need or get to use them, but still.

2016-10-27 11:48 UTC, jokva requested changes

2016-10-27 11:48 UTC, jokva commented on opm/output/eclipse/RegionCache.cpp
> +    RegionCache::RegionCache(const EclipseState& state, const EclipseGrid& grid) {
My only wonder w.r.t. this is the name cache - why does it matter that it's a cache? Describing functionality and all.

2016-10-27 11:48 UTC, jokva commented on opm/output/eclipse/RegionCache.hpp
> +        std::vector<size_t> cells_empty;
These should probably be static members to save some space.

2016-10-27 11:48 UTC, jokva commented on tests/test_Summary.cpp
> +        solution = make_solution( es.getInputGrid());
Not really related to this PR, but anyone know why solution isn't just in the init list?

2016-10-27 11:48 UTC, jokva commented on tests/test_Summary.cpp
> +    /*BOOST_CHECK_CLOSE(ecl_sum_get_general_var( resp , 2 , "RGPT:1" ) ,
Commented out.

2016-10-28 12:48 UTC, jokva commented
Superseded by https://github.com/OPM/opm-output/pull/122

2016-10-28 12:48 UTC, closed without merging